### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by kodeine** [danmt/service-discovery#1]
Hello,
so i was following your tutorial, each app will be on its own docker? Can you please write an example docker file as well. I am still new to microservices and trying to absorb all the knowledge i can.

Thank you for taking the time to write this wonderful article.

**Comment by danmt** [comment]
Hey there, I never got to finish this article, I'm glad you could follow up without too much step by step explanation. I have to admit I'm not really experienced with Docker, I'm gonna owe you that. Feel free to fork the project and create a PR. 

Thanks for reading, I suppose I should wrap this one up.
